import math
# print(math.ceil(0.2))
# print(math.ceil(1.3))
# print(math.ceil(2.5))
# print(math.ceil(-8.7))
# print(math.ceil(25.8))
# print(math.ceil(15.0))
# print(math.exp(1))
# print(math.exp(2))
# print(math.exp(3))
# print(math.factorial(0))
# print(math.factorial(1))
# print(math.factorial(2))
# print(math.factorial(3))
# print(math.factorial(4))
# print(math.factorial(5))
# print(math.factorial(6))
# print(math.floor(36.5))
# print(math.floor(36.8))
# print(math.floor(36.7))
# print(math.floor(-36.4))
# print(math.ceil(26.8))
# print(math.floor(26.8))
# print(math.ceil(46.5))
# print(math.floor(46.5))

# a=math.pow(4,4)
# b=4**4
# print(a,type(a))
# print(b,type(b))
# print(math.pi)
# print(math.pi*3)
# print(math.pi*4**2)
# print(math.sqrt(4))
# print(math.sqrt(9))
# print(math.sqrt(12.5))
# print(math.sqrt(35))
# print(math.sqrt(36))
# a=0  # 0 will give 0 if used isqrt
# b=1  # 1 to 3 will give 1 if used isqrt
# c=5  # 4 to 8 will give 2 if used isqrt
# d=11 # 9 to 15 will give 3 if used isqrt
# e=22 # 16 to 24 will give 4 if used isqrt
# f=34 # 25 to 35 will give 5 if used isqrt
# print(math.isqrt(a))
# print(math.isqrt(b))
# print(math.isqrt(c))
# print(math.isqrt(d))
# print(math.isqrt(e))
# print(math.isqrt(f))

# v=[1,2,3,4,5]
# print(sum(v))
# print(math.fsum(v))
# print(math.prod(v))
# print(int(math.fsum(v)))
# a=27%5
# print(a)
# print(math.fmod(27,5))
# n=-7
# print(abs(n))
# print(math.fabs(n))
# print(math.sin(45))
# print(math.cos(45))
# print(math.tan(45))
# print(math.trunc(4.55))
# print(math.trunc(-6.55))
# print(math.gcd(16,13))
# print(math.gcd(16,15))
# print(math.gcd(16,19))
# print(math.gcd(16,21))
# print(math.gcd(16,25))
# print(math.gcd(16,29))
# print(math.gcd(16,31))
# print(math.gcd(16,18))
# print(math.gcd(16,24))
# print(math.gcd(26,64))
# print(math.gcd(54,76))
# print(math.gcd(12,18))
# print(math.lcm(4,18))
# print(math.lcm(6,16))
# print(math.lcm(2,14))

# print(dir(math))